version: 2.1

jobs:
  click-and-check:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            sudo pip install selenium
            sudo pip install requests
            sudo pip install pytest
      - run:
          command: python tests/test_selenium.py
  deploy:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            scp -r -o StrictHostKeyChecking=no ./ ubuntu@ec2-3-21-58-106.us-east-2.compute.amazonaws.com:/home/ubuntu/cci-exercise/
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-21-58-106.us-east-2.compute.amazonaws.com "./deploy.sh"

workflows:
  click-and-check-workflow:
    jobs:
      - click-and-check
      - deploy:
            requires:
                - click-and-check
