version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  click-and-check:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: echo $THE_PASSWORD
      - run: mkdir test-reports
      - run:
          command: |
            pip install pipenv
            pipenv install
            pip install selenium
            pip install requests
            pip install pytest
      - run:
          command: python tests/*

workflows:
  click-and-check-workflow:
    jobs:
      - click-and-check:
            context:
                - "Secret Things"
      - hold:
            type: approval
            requires:
                - click-and-check
      - heroku/deploy-via-git:
          requires:
            - hold
          filters:
            branches:
              only: main
