version: 2.1

jobs:
  click-and-check:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: echo $THE_PASSWORD
      - run: mkdir test-reports
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            sudo pip install selenium
            sudo pip install requests
            sudo pip install pytest
      - run:
          command: python tests/test_selenium.py
  deploy:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: echo "Hello world"
            

workflows:
  click-and-check-workflow:
    jobs:
      - click-and-check:
            context:
                - "Secret Things"
      - hold:
            type: approval
      - deploy:
            requires:
                - click-and-check
